var ajaxurl							= pie_pr_dec_vars.ajaxURL;
var piereg_current_date				= pie_pr_dec_vars.dateY;
var piereg_startingDate				= pie_pr_dec_vars.piereg_startingDate;
var piereg_endingDate				= pie_pr_dec_vars.piereg_endingDate;
var piereg_pass_str_meter_string 	= new Array(pie_pr_dec_vars.pass_strength_indicator_label,
														 pie_pr_dec_vars.pass_very_weak_label,
														 pie_pr_dec_vars.pass_weak_label,
														 pie_pr_dec_vars.pass_medium_label,
														 pie_pr_dec_vars.pass_strong_label,
														 pie_pr_dec_vars.pass_mismatch_label
														 );
var piereg_validation_engn 			= new Array(
										 pie_pr_dec_vars.ValidationMsgText1,
										 pie_pr_dec_vars.ValidationMsgText2,
										 pie_pr_dec_vars.ValidationMsgText3,
										 pie_pr_dec_vars.ValidationMsgText4,
										 pie_pr_dec_vars.ValidationMsgText5,
										 pie_pr_dec_vars.ValidationMsgText6,
										 pie_pr_dec_vars.ValidationMsgText7,
										 pie_pr_dec_vars.ValidationMsgText8,
										 pie_pr_dec_vars.ValidationMsgText9,
										 pie_pr_dec_vars.ValidationMsgText10,
										 pie_pr_dec_vars.ValidationMsgText11,
										 pie_pr_dec_vars.ValidationMsgText12,
										 pie_pr_dec_vars.ValidationMsgText13,
										 pie_pr_dec_vars.ValidationMsgText14,
										 pie_pr_dec_vars.ValidationMsgText15,
										 pie_pr_dec_vars.ValidationMsgText16,
										 pie_pr_dec_vars.ValidationMsgText17,
										 pie_pr_dec_vars.ValidationMsgText18,
										 pie_pr_dec_vars.ValidationMsgText19,
										 pie_pr_dec_vars.ValidationMsgText20,
										 pie_pr_dec_vars.ValidationMsgText21,
										 pie_pr_dec_vars.ValidationMsgText22,
										 pie_pr_dec_vars.ValidationMsgText23,
										 pie_pr_dec_vars.ValidationMsgText24,
										 pie_pr_dec_vars.ValidationMsgText25,
										 pie_pr_dec_vars.ValidationMsgText26,
										 pie_pr_dec_vars.ValidationMsgText27,
										 pie_pr_dec_vars.ValidationMsgText28,
										 pie_pr_dec_vars.ValidationMsgText29,
										 pie_pr_dec_vars.ValidationMsgText30,
										 pie_pr_dec_vars.ValidationMsgText31,
										 pie_pr_dec_vars.ValidationMsgText32,
										 pie_pr_dec_vars.ValidationMsgText33,
										 pie_pr_dec_vars.ValidationMsgText34,
										 pie_pr_dec_vars.ValidationMsgText35,
										 pie_pr_dec_vars.ValidationMsgText36,
										 pie_pr_dec_vars.ValidationMsgText37,
										 pie_pr_dec_vars.ValidationMsgText38,
										 pie_pr_dec_vars.ValidationMsgText39,
										 pie_pr_dec_vars.ValidationMsgText40,
										 pie_pr_dec_vars.ValidationMsgText41,
										 pie_pr_dec_vars.ValidationMsgText42,
										 pie_pr_dec_vars.ValidationMsgText43,
										 pie_pr_dec_vars.ValidationMsgText44,
										 pie_pr_dec_vars.ValidationMsgText45,
										 pie_pr_dec_vars.ValidationMsgText46,
										 pie_pr_dec_vars.ValidationMsgText47,
										 pie_pr_dec_vars.ValidationMsgText48,
										 pie_pr_dec_vars.ValidationMsgText49,
										 pie_pr_dec_vars.ValidationMsgText50,
										 pie_pr_dec_vars.ValidationMsgText51,
										 pie_pr_dec_vars.ValidationMsgText52,
										 pie_pr_dec_vars.ValidationMsgText53,
										 pie_pr_dec_vars.ValidationMsgText54,
										 pie_pr_dec_vars.ValidationMsgText55,
										 pie_pr_dec_vars.ValidationMsgText56,
										 pie_pr_dec_vars.ValidationMsgText57,
										 pie_pr_dec_vars.ValidationMsgText58
										);
piereg_validation_engn['delete'] 	= pie_pr_dec_vars.ValidationMsgText59;
piereg_validation_engn['edit'] 		= pie_pr_dec_vars.ValidationMsgText60;
